# Upstream server to redirect authenticated requests
upstreams = "http://172.17.0.2:8888"

# Secret to encrypt cookies
cookie_secret = "testing123456"
# Cookies expire lifetime in ms (8h default mentioned below)
cookie_expire = 28800000

# Client ID and secret for this application, you need this to get
# from your authentication provider e.g. Dataporten, Github, Google
provider = "dataporten"
client_id = "client ID"
client_secret = "client Secret

# List of comma seperated groups ID for dataporten 
# only Users who are members of this group will be allowed
# To allow everybody comment this parameter
dataporten_groups = "test:group"

# Https address as to where the proxy will listen for connection
# By default it listen on the below mentioned address, specify either
# http or https address
http_address = "127.0.0.1:4180"
#https_address = "127.0.0.1:4180"

# SSL Configration, to enable uncomment below options and 
# specify correct certificate path. Also make sure to switch
# cookie to be secure by changing flag to true
#tls_cert_file = "my.crt"
#tls_key_file = "my.key"
cookie_secure = false

# Miscelleneous settings
email_domains = "*"
skip_provider_button = true
footer = "-"
request_logging = false